name: Format, lint & test
on: [push,workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TOX_PARALLEL_NO_SPINNER: 1
    steps:
      - uses: actions/checkout@v3
      - name: Install Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: Install Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - run: python -m pip install tox
      - run: tox --parallel -e checkformatting,lint,py310-tests,py310-functests
      - run: tox -e py39-tests,py38-tests,coverage,py39-functests,py38-functests
